CREATE TABLE `auditVisuals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`auditId` int NOT NULL,
	`visualType` varchar(100) NOT NULL,
	`imageUrl` varchar(512) NOT NULL,
	`s3Key` varchar(512) NOT NULL,
	`description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `auditVisuals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `audits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`websiteUrl` varchar(512) NOT NULL,
	`primaryLocation` varchar(255) NOT NULL,
	`primaryNiche` varchar(100) NOT NULL,
	`nicheDescription` text,
	`leadSources` text,
	`runsPaidAds` varchar(20),
	`hasLocalListing` varchar(20),
	`activeOnSocial` varchar(20),
	`usesAutomation` varchar(20),
	`hasCallCoverage` varchar(20),
	`monthlyVisitors` int,
	`monthlyLeads` int,
	`avgRevenuePerClient` int,
	`businessGoals` text,
	`painPoints` text,
	`gbpAuditResults` text,
	`seoAuditResults` text,
	`competitiveResults` text,
	`aeoResults` text,
	`leadCaptureResults` text,
	`followUpResults` text,
	`executiveSummary` text,
	`keyFindings` text,
	`recommendations` text,
	`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`pdfUrl` varchar(512),
	`emailSent` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `audits_id` PRIMARY KEY(`id`)
);
